### ISSUE TITLE
Suggestion: Translate Documentation to English

### ISSUE THREAD

**Issue by emkbt** [Lanelle64/JDLV-Raphael-TD5#3]
### Description:
The documentation for this project is currently in French, which may limit its accessibility to a wider audience. This issue proposes the translation of the documentation to English to make it more inclusive and reach a broader community of users and developers.

### Proposed Solution:
Translate the existing French documentation to English. This involves updating the README, code comments, and any other relevant documentation files. Ensure that the translation accurately reflects the information in the original French documentation.

### Additional Notes:
- Consider using online translation tools for an initial translation and then refining the text for clarity and accuracy.
- Keep the translation in sync with any updates or changes made to the original French documentation.
- Encourage community members who are proficient in both languages to contribute to the translation efforts.

**Comment by Lanelle64** [comment]
Thank you for proposing your help for the translation!
